networks:
  traefik_proxy:
    external: true

services:
  openspeedtest:
    image: openspeedtest/latest
    container_name: openspeedtest
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: "${TZ:-America/Los_Angeles}"
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy
      
      # Service
      - traefik.http.services.speedtest.loadbalancer.server.port=3000
      
      # Router
      - traefik.http.routers.speedtest.rule=Host(`speedtest.stephandkyle.us`)
      - traefik.http.routers.speedtest.entrypoints=websecure
      - traefik.http.routers.speedtest.tls.certresolver=le-dns
      - traefik.http.routers.speedtest.middlewares=authentik@docker

      # Homepage discovery
      - homepage.group=Quick Links
      - homepage.name=Open Speedtest
      - homepage.description=Self-hosted internet speed test
      - homepage.icon=sh-openspeedtest
      - homepage.href=https://speedtest.stephandkyle.us

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=https://speedtest.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/openspeedtest.png