networks:
  traefik_proxy:
    external: true
  authentik_net:
    internal: true

services:
  authentik-postgres:
    image: postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    user: "${PUID:-99}:${PGID:-100}"
    networks:
      - authentik_net
    environment:
      POSTGRES_USER: "${AUTHENTIK_DB_USER:-authentik}"
      POSTGRES_PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      POSTGRES_DB: "${AUTHENTIK_DB_NAME:-authentik}"
    volumes:
      - /mnt/user/appdata/authentik/postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s

  authentik-server:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-server
    restart: unless-stopped
    user: "${PUID:-99}:${PGID:-100}"
    command: server
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    networks:
      - traefik_proxy
      - authentik_net
    environment:
      # --- Core settings ---
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"

      # --- Database (Postgres) ---
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgres"
      AUTHENTIK_POSTGRESQL__USER: "${AUTHENTIK_DB_USER:-authentik}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      AUTHENTIK_POSTGRESQL__NAME: "${AUTHENTIK_DB_NAME:-authentik}"

      # --- Redis ---
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_REDIS__PORT: "6379"

    volumes:
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/custom-templates:/templates

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # Router
      - "traefik.http.routers.authentik.rule=Host(`auth.stephandkyle.us`)"
      - "traefik.http.routers.authentik.entrypoints=websecure"
      - "traefik.http.routers.authentik.tls.certresolver=le-dns"

      # Service
      - "traefik.http.services.authentik.loadbalancer.server.port=9000"

      # Homepage discovery
      - "homepage.group=Infra"
      - "homepage.name=Authentik"
      - "homepage.icon=si-auth0"
      - "homepage.href=https://auth.stephandkyle.us"
      - "homepage.description=SSO / identity provider"

      # Unraid UI
      - "net.unraid.docker.webui=https://auth.stephandkyle.us"

  authentik-worker:
    image: ghcr.io/goauthentik/server:latest
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    networks:
      - authentik_net
    environment:
      # --- Core settings ---
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"

      # --- Database (Postgres) ---
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgres"
      AUTHENTIK_POSTGRESQL__USER: "${AUTHENTIK_DB_USER:-authentik}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      AUTHENTIK_POSTGRESQL__NAME: "${AUTHENTIK_DB_NAME:-authentik}"

      # --- Redis ---
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_REDIS__PORT: "6379"

    user: "${PUID:-99}:${PGID:-100}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/custom-templates:/templates
      - /mnt/user/appdata/authentik/certs:/certs

  authentik-redis:
    image: redis:7-alpine
    container_name: authentik-redis
    user: "${PUID:-99}:${PGID:-100}"
    restart: unless-stopped
    networks:
      - authentik_net
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - /mnt/user/appdata/authentik/redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s