networks:
  traefik_proxy:
    external: true
  authentik_net:
    internal: true

services:
  authentik-postgres:
    image: postgres:16-alpine
    container_name: authentik-postgres
    restart: unless-stopped
    user: "${PUID:-99}:${PGID:-100}"
    networks:
      - authentik_net
    environment:
      POSTGRES_USER: "${AUTHENTIK_DB_USER:-authentik}"
      POSTGRES_PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      POSTGRES_DB: "${AUTHENTIK_DB_NAME:-authentik}"
    volumes:
      - /mnt/user/appdata/authentik/postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 30s
      retries: 5
      start_period: 20s
      test:
        - CMD-SHELL
        - pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}
      timeout: 5s
    labels:
      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
      
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/postgresql.png

  authentik-redis:
    image: redis:7-alpine
    container_name: authentik-redis
    user: "${PUID:-99}:${PGID:-100}"
    restart: unless-stopped
    networks:
      - authentik_net
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    volumes:
      - /mnt/user/appdata/authentik/redis:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
    labels:
      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
      
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/redis.png

  authentik-server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.1}
    container_name: authentik-server
    restart: unless-stopped
    user: "${PUID:-99}:${PGID:-100}"
    command: server
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    networks:
      - traefik_proxy
      - authentik_net
    environment:
      # --- Core settings ---
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"

      # --- Database (Postgres) ---
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgres"
      AUTHENTIK_POSTGRESQL__USER: "${AUTHENTIK_DB_USER:-authentik}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      AUTHENTIK_POSTGRESQL__NAME: "${AUTHENTIK_DB_NAME:-authentik}"

      # --- Email ---
      AUTHENTIK_EMAIL__HOST: "mailgun"
      AUTHENTIK_EMAIL__PORT: "2500"
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__USERNAME: ""
      AUTHENTIK_EMAIL__PASSWORD: ""
      AUTHENTIK_EMAIL__FROM: "noreply@stephandkyle.us"
      AUTHENTIK_EMAIL__FROM_NAME: "Calcifer"

      # --- Redis ---
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_REDIS__PORT: "6379"

    volumes:
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/custom-templates:/templates

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.authentik.loadbalancer.server.port=9000

      # Router
      - traefik.http.routers.authentik.rule=Host(`auth.stephandkyle.us`)
      - traefik.http.routers.authentik.entrypoints=websecure
      - traefik.http.routers.authentik.tls.certresolver=le-dns

      # Homepage discovery
      - homepage.group=Inf Stack 1
      - homepage.name=Authentik
      - homepage.icon=sh-authentik
      - homepage.href=https://auth.stephandkyle.us

      # Homepage widget
      - homepage.widget.type=authentik
      - homepage.widget.url=http://authentik-server:9000
      - homepage.widget.key=${AUTHENTIK_API_KEY}

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=https://auth.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/authentik.png

  authentik-worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:${AUTHENTIK_TAG:-2025.10.1}
    container_name: authentik-worker
    restart: unless-stopped
    command: worker
    depends_on:
      authentik-postgres:
        condition: service_healthy
      authentik-redis:
        condition: service_healthy
    networks:
      - authentik_net
    environment:
      # --- Core settings ---
      AUTHENTIK_SECRET_KEY: "${AUTHENTIK_SECRET_KEY}"

      # --- Database (Postgres) ---
      AUTHENTIK_POSTGRESQL__HOST: "authentik-postgres"
      AUTHENTIK_POSTGRESQL__USER: "${AUTHENTIK_DB_USER:-authentik}"
      AUTHENTIK_POSTGRESQL__PASSWORD: "${AUTHENTIK_DB_PASSWORD}"
      AUTHENTIK_POSTGRESQL__NAME: "${AUTHENTIK_DB_NAME:-authentik}"

      # --- Redis ---
      AUTHENTIK_REDIS__HOST: "authentik-redis"
      AUTHENTIK_REDIS__PORT: "6379"

      # --- Email ---
      AUTHENTIK_EMAIL__HOST: "mailgun"
      AUTHENTIK_EMAIL__PORT: "2500"
      AUTHENTIK_EMAIL__USE_TLS: "false"
      AUTHENTIK_EMAIL__USE_SSL: "false"
      AUTHENTIK_EMAIL__USERNAME: ""
      AUTHENTIK_EMAIL__PASSWORD: ""
      AUTHENTIK_EMAIL__FROM: "noreply@stephandkyle.us"
      AUTHENTIK_EMAIL__FROM_NAME: "Calcifer"

    user: "${PUID:-99}:${PGID:-100}"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/user/appdata/authentik/media:/media
      - /mnt/user/appdata/authentik/custom-templates:/templates
      - /mnt/user/appdata/authentik/certs:/certs

    labels:
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/authentik.png

  authentik-outpost:
    image: ghcr.io/goauthentik/proxy:${AUTHENTIK_TAG:-2025.10.1}
    container_name: authentik-outpost
    restart: unless-stopped
    depends_on:
      authentik-server:
        condition: service_healthy
    networks:
      - traefik_proxy
      - authentik_net
    environment:
      AUTHENTIK_HOST_BROWSER: "https://auth.stephandkyle.us"
      AUTHENTIK_HOST: "http://authentik-server:9000"
      AUTHENTIK_TOKEN: "${AUTHENTIK_OUTPOST_TOKEN}"

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Route just for the outpost's own endpoints
      - traefik.http.routers.authentik-outpost.rule=Host(`auth.stephandkyle.us`) && PathPrefix(`/outpost.goauthentik.io/`)
      - traefik.http.routers.authentik-outpost.entrypoints=web
      - traefik.http.services.authentik-outpost.loadbalancer.server.port=9000

      # Forward-auth middleware definition
      - traefik.http.middlewares.authentik.forwardauth.address=http://authentik-outpost:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.authentik.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.authentik.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid,X-authentik-jwt,X-authentik-meta-jwks,X-authentik-meta-outpost,X-authentik-meta-provider,X-authentik-meta-app,X-authentik-meta-version

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/authentik.png