networks:
  traefik_proxy:
    external: true

services:
  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: "${TZ:-America/Los_Angeles}"
      
      # General Configuration
      BASE_URL: "recipes.stephandkyle.us"
      ALLOW_SIGNUP: "false"
      ALLOW_PASSWORD_LOGIN: "false"

      # Email Configuration
      SMTP_HOST: "mailgun"
      SMTP_PORT: "2500"
      SMTP_AUTH_STRATEGY: "none"
      SMTP_FROM_NAME: "Steph and Kyle Recipies"
      SMTP_FROM_EMAIL: "mealie@stephandkyle.us"

      # OpenAI Configuration
      OPENAI_API_KEY: "${OPENAI_API_KEY}"

       # OIDC Configuration
      OIDC_AUTH_ENABLED: "true"
      OIDC_PROVIDER_NAME: "authentik"
      OIDC_CONFIGURATION_URL: https://auth.stephandkyle.us/application/o/${OIDC_APP_SLUG:-mealie}/.well-known/openid-configuration
      OIDC_CLIENT_ID: "${OIDC_CLIENT_ID}"
      OIDC_CLIENT_SECRET: "${OIDC_CLIENT_SECRET}"
      OIDC_SIGNUP_ENABLED: true
      OIDC_USER_GROUP: "mealie-users"
      OIDC_ADMIN_GROUP: "mealie-admins"
      OIDC_AUTO_REDIRECT: true
      OIDC_REMEMBER_ME: true

    volumes:
      - /mnt/user/appdata/mealie:/app/data
    labels:  
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.mealie.loadbalancer.server.port=9000

      # Router
      - traefik.http.routers.mealie.rule=Host(`recipes.stephandkyle.us`)
      - traefik.http.routers.mealie.entrypoints=websecure
      - traefik.http.routers.mealie.tls.certresolver=le-dns

      # Homepage discovery
      - homepage.group=Home Services
      - homepage.name=Recipes
      - homepage.icon=sh-mealie
      - homepage.href=https://recipes.stephandkyle.us

      # Homepage widget
      - homepage.widget.type=mealie
      - homepage.widget.url=http://mealie:9000
      - homepage.widget.key=${MEALIE_API_KEY}
      - homepage.widget.version=2

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=https://recipes.stephandkyle.us
      - net.unraid.docker.icon=https://logo.svgcdn.com/simple-icons/mealie-dark.png