networks:
  traefik_proxy:
    external: true

services:
  s3backup:
    image: joch/s3backup:latest
    container_name: s3backup
    restart: unless-stopped
    volumes:
      - /mnt/user/media/photos:/data/photos:ro
      - /mnt/user/public/kyle:/data/kyle:ro
      - /mnt/user/public/steph:/data/steph:ro
      - /mnt/user/public/records:/data/records:ro
      - /mnt/user/public/backups:/data/backups:ro
    environment:
      - S3PATH=s3://backup.stephandkyle.us/
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - CRON_SCHEDULE=0 * * * *
      - TZ=America/Los_Angeles
    labels:
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/amazon-s3.png

  duplicacy:
    image: saspus/duplicacy-web:latest
    container_name: duplicacy
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/user/appdata/duplicacy/config:/config
      - /mnt/user/appdata/duplicacy/cache:/cache
      - /mnt/user:/mnt/user:ro
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.duplicacy.loadbalancer.server.port=3875

      # Router
      - traefik.http.routers.duplicacy.rule=Host(`backup.stephandkyle.us`)
      - traefik.http.routers.duplicacy.entrypoints=websecure
      - traefik.http.routers.duplicacy.tls.certresolver=le-dns
      - traefik.http.routers.duplicacy.middlewares=ip-allowlist@docker

      # Unraid UI
      - net.unraid.docker.webui=https://backup.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/duplicacy.png