networks:
  traefik_proxy:
    external: true

volumes:
  media:
    external: true

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    networks:
      - traefik_proxy
    environment:
      TZ: "${TZ:-America/Los_Angeles}"

      # OpenVPN / Provider
      VPN_SERVICE_PROVIDER: "privado"
      OPENVPN_USER: "${OPENVPN_USER}"
      OPENVPN_PASSWORD: "${OPENVPN_PASSWORD}"

      # Target region — flexible, simple
      SERVER_COUNTRIES: "United States"

      # Allow Traefik to reach UIs
      FIREWALL_INPUT_PORTS: "8080,8081"
      FIREWALL_INPUT_SUBNETS: "172.21.0.0/16"

      # Allow me some freedom
      BLOCK_MALICIOUS: "off"

    healthcheck:
      test: ["CMD-SHELL", "ip -4 addr show dev tun0 | grep -q 'inet ' && nc -zw2 1.1.1.1 80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
      
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_proxy"

      # Router — qBittorrent
      - "traefik.http.routers.qb.rule=Host(`qb.stephandkyle.us`)"
      - "traefik.http.routers.qb.entrypoints=websecure"
      - "traefik.http.routers.qb.tls.certresolver=le-dns"
      - "traefik.http.routers.qb.middlewares=ip-allowlist@docker"
      - "traefik.http.routers.qb.service=qb-svc"

      # Service - qBittorrent
      - "traefik.http.services.qb-svc.loadbalancer.server.port=8081"

      # Router — SABnzbd
      - "traefik.http.routers.sab.rule=Host(`sab.stephandkyle.us`)"
      - "traefik.http.routers.sab.entrypoints=websecure"
      - "traefik.http.routers.sab.tls.certresolver=le-dns"
      - "traefik.http.routers.sab.middlewares=ip-allowlist@docker"
      - "traefik.http.routers.sab.service=sab-svc"

      # Service - SABnzbd
      - "traefik.http.services.sab-svc.loadbalancer.server.port=8080"

      # Unraid UI
      - "org.unraid.docker.webui="
      - "org.unraid.docker.icon=https://raw.githubusercontent.com/qdm12/gluetun/master/.github/icon.png"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: "${TZ:-America/Los_Angeles}"
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - media:/media
    restart: unless-stopped
    labels:
      # Unraid UI
      - "org.opencontainers.image.title=qBittorrent"
      - "org.opencontainers.image.description=VPN-backed qBittorrent client"
      - "org.opencontainers.image.documentation=https://github.com/linuxserver/docker-qbittorrent"
      - "org.unraid.docker.webui=https://qb.stephandkyle.us"
      - "org.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent.png"
  
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: "${TZ:-America/Los_Angeles}"
    volumes:
      - /mnt/user/appdata/sabnzbd:/config
      - media:/media
    restart: unless-stopped
    labels:
      # Unraid UI
      - "org.opencontainers.image.title=SABnzbd"
      - "org.opencontainers.image.description=VPN-backed SABnzbd client"
      - "org.opencontainers.image.documentation=https://github.com/linuxserver/docker-sabnzbd"
      - "org.unraid.docker.webui=https://sab.stephandkyle.us"
      - "org.unraid.docker.icon=https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sabnzbd.png"