networks:
  traefik_proxy:
    external: true
  paperless_net:
    internal: true

services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    networks:
      - traefik_proxy
      - paperless_net

    environment:
      # UID/GID that should own files on disk
      USERMAP_UID: "${USERMAP_UID:-99}"
      USERMAP_GID: "${USERMAP_GID:-100}"

      # Timezone + base URL
      PAPERLESS_TIME_ZONE: "${TZ:-America/Los_Angeles}"
      PAPERLESS_URL: "https://docs.stephandkyle.us"

      # Redis (used even when DB is SQLite)
      PAPERLESS_REDIS: "redis://paperless-redis:6379"

      # Optional, but nice defaults
      PAPERLESS_OCR_LANGUAGE: "eng"
      # PAPERLESS_SECRET_KEY: "set-me-in-.env-for-real"

      # Authentik Auth
      PAPERLESS_ENABLE_ALLAUTH: true
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "authentik",
                  "client_id": "${OAUTH_CLIENT_ID}",
                  "secret": "${OAUTH_SECRET}",
                  "settings": {
                    "server_url": "https://auth.stephandkyle.us/application/o/paperless/.well-known/openid-configuration",
                    "claims": {"username": "email"}
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": "True"
            }
          }
      PAPERLESS_AUTO_LOGIN: true
      PAPERLESS_AUTO_CREATE: true
      PAPERLESS_LOGOUT_REDIRECT_URL: "https://auth.stephandkyle.us/application/o/paperless/end-session/"

    volumes:
      - /mnt/user/appdata/paperless:/usr/src/paperless/data
      - /mnt/user/public/paperless/media:/usr/src/paperless/media
      - /mnt/user/public/paperless/export:/usr/src/paperless/export
      - /mnt/user/public/paperless/consume/:/usr/src/paperless/consume

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.paperless.loadbalancer.server.port=8000
      
      # Router
      - traefik.http.routers.paperless.rule=Host(`docs.stephandkyle.us`)
      - traefik.http.routers.paperless.entrypoints=websecure
      - traefik.http.routers.paperless.tls.certresolver=le-dns

      # Homepage discovery
      - homepage.group=Home Services
      - homepage.name=Documents
      - homepage.icon=sh-paperless-ngx
      - homepage.href=https://docs.stephandkyle.us

      # Homepage widget
      - homepage.widget.type=paperlessngx
      - homepage.widget.url=http://paperless:8000
      - homepage.widget.key=${PAPERLESS_API_KEY}

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=https://docs.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/paperless-ngx.png

  paperless-redis:
    image: redis:7-alpine
    container_name: paperless-redis
    restart: unless-stopped
    networks:
      - paperless_net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s

    labels:
    # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
      
    # Unraid UI metadata
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/redis.png