volumes:
  media:
    external: true

networks:
  traefik_proxy:
    external: true

services:
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    restart: unless-stopped
    network_mode: host

    # Intel QuickSync Device 
    devices: 
      - /dev/dri:/dev/dri

    environment:
      # --- Identities / permissions ---
      PLEX_UID: "${PUID:-99}"
      PLEX_GID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: America/Los_Angeles
    volumes:
      # Plex config / metadata
      - /mnt/user/appdata/plex:/config

      # Your main media volume (matches the rest of your stacks)
      - media:/data

      # Transcode dir – /tmp = in-RAM on Unraid if you want that
      # You can change to /mnt/user/appdata/plex/transcode if you prefer disk
      - /tmp:/transcode

    labels:
      # Homepage discovery
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=sh-plex
      - homepage.href=http://app.plex.tv
      - homepage.description=Media server (Plex)

      # Homepage widget
      - homepage.widget.type=plex
      - homepage.widget.url=http://192.168.1.8:32400
      - homepage.widget.key=${PLEX_TOKEN}

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=http://app.plex.tv
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/plex.png

  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    networks:
      - traefik_proxy
    environment:
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      TZ: America/Los_Angeles
    volumes:
      - /mnt/user/appdata/audiobookshelf:/config
      - media:/media
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.audiobookshelf.loadbalancer.server.port=80
  
      # Router
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.stephandkyle.us`)
      - traefik.http.routers.audiobookshelf.entrypoints=websecure
      - traefik.http.routers.audiobookshelf.tls.certresolver=le-dns
      - traefik.http.routers.audiobookshelf.middlewares=ip-allowlist@docker

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
  
      # Homepage discovery
      - homepage.group=Media
      - homepage.name=Audiobooks
      - homepage.icon=sh-audiobookshelf
      - homepage.href=https://audiobooks.stephandkyle.us
      - homepage.description=Audiobook & podcast library

      # Homepage widget
      - homepage.widget.type=audiobookshelf
      - homepage.widget.url=http://audiobookshelf:80
      - homepage.widget.key=${AUDIOBOOKSHELF_TOKEN}
      - homepage.widget.fields=books,booksDuration
  
      # Unraid UI
      - net.unraid.docker.webui=https://audiobooks.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/audiobookshelf.png