networks:
  traefik_proxy:
    external: true
  immich_net:
    internal: true

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    container_name: immich-server
    user: "${PUID:-99}:${PGID:-100}"
    restart: unless-stopped
    depends_on:
      - immich-postgres
      - immich-redis
      # - immich-ml   # uncomment if you keep the ML service
    networks:
      - traefik_proxy
      - immich_net

    environment:
      # Standard Unraid-style ownership
      PUID: "${PUID:-99}"
      PGID: "${PGID:-100}"
      UMASK: "${UMASK:-002}"
      TZ: "${TZ:-America/Los_Angeles}"

      # Database (Postgres)
      DB_HOSTNAME: "immich-postgres"
      DB_PORT: "5432"
      DB_USERNAME: "${IMMICH_DB_USER:-immich}"
      DB_PASSWORD: "${IMMICH_DB_PASSWORD}"
      DB_DATABASE_NAME: "${IMMICH_DB_NAME:-immich}"

      # Redis
      REDIS_HOSTNAME: "immich-redis"
      REDIS_PORT: "6379"

      # Optional tuning
      # IMMICH_LOG_LEVEL: "log"

    volumes:
      # Originals & generated media
      # Adjust the left side to wherever you want Immich to store photos/videos
      - /mnt/user/media/photos:/data

    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_proxy

      # Service
      - traefik.http.services.immich.loadbalancer.server.port=2283

      # Router
      - traefik.http.routers.immich.rule=Host(`photos.stephandkyle.us`)
      - traefik.http.routers.immich.entrypoints=websecure
      - traefik.http.routers.immich.tls.certresolver=le-dns
      - traefik.http.routers.immich.middlewares=ip-allowlist@docker

      # Homepage discovery
      - homepage.group=Media
      - homepage.name=Photos
      - homepage.icon=sh-immich
      - homepage.href=https://photos.stephandkyle.us

      # Homepage widget
      - homepage.widget.type=immich
      - homepage.widget.url=http://immich-server:2283
      - homepage.widget.key=${IMMICH_API_KEY}
      - homepage.widget.version=2

      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true

      # Unraid UI
      - net.unraid.docker.webui=https://photos.stephandkyle.us
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich.png

  # immich-machine-learning:
  #   image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
  #   container_name: immich-machine-learning
  #   restart: unless-stopped
  #   networks:
  #     - immich_net
  #   environment:
  #     PUID: "${PUID:-99}"
  #     PGID: "${PGID:-100}"
  #     UMASK: "${UMASK:-002}"
  #     TZ: "${TZ:-America/Los_Angeles}"
  #   volumes:
  #     - /mnt/user/appdata/immich/ml-cache:/cache
  #   labels:
  #     # Watchtower Updates
  #     - com.centurylinklabs.watchtower.enable=true
      
  #     # Unraid UI
  #     - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/immich-power-tools.png

  immich-postgres:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0
    container_name: immich-postgres
    restart: unless-stopped
    networks:
      - immich_net
    environment:
      POSTGRES_DB: "${IMMICH_DB_NAME:-immich}"
      POSTGRES_USER: "${IMMICH_DB_USER:-immich}"
      POSTGRES_PASSWORD: "${IMMICH_DB_PASSWORD}"
    volumes:
      - /mnt/user/appdata/immich/postgres:/var/lib/postgresql/data
    shm_size: "128mb"
    labels:
      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
      
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/postgresql.png

  immich-redis:
    image: redis:7-alpine
    container_name: immich-redis
    restart: unless-stopped
    networks:
      - immich_net
    labels:
      # Watchtower Updates
      - com.centurylinklabs.watchtower.enable=true
      
      # Unraid UI
      - net.unraid.docker.icon=https://cdn.jsdelivr.net/gh/selfhst/icons/png/redis.png